# Generated by Django 6.0.5 on 2026-05-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotesImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("topic_name", models.CharField(max_length=200)),
                ("raw_notes", models.TextField(help_text="Paste your raw notes here")),
                (
                    "formatted_notes",
                    models.JSONField(
                        blank=True, help_text="Auto-formatted notes data", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("imported", "Imported"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("notes_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Notes Import Session",
                "verbose_name_plural": "Notes Import Sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
